### ISSUE TITLE
Pt3d Supports variadic instantiation. Python should too.

### ISSUE THREAD

**Issue by Tsubashi** [Aquaveo/xmscore#10]
The helper function that converts from tuples to Pt3d currently requires 3-tuples, but Pt3d doesn't necessarily. We definitely should support 2-tuples, and possibly 1-tuples and empty sets. These should call the appropriate constructor on Pt3d.

https://github.com/Aquaveo/xmscore/blob/d50d2fd618d2ac8b7f87118f7305cd6f1e71b58c/xmscore/python/misc/PyUtils.cpp#L25

**Comment by alemon-aquaveo** [comment]
approved
